---
title: "Estado de Pago"
author: "MERC Consultora"
date: 'Fecha de emisión: `r format(Sys.Date(), format = "%d-%m-%Y")`'
output: html_document
params:
  data_source: ta
  resumen: tb
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path(getwd(), "images","merc_720.png")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; height:80px; width:200px')
```

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(gt)
knitr::opts_chunk$set(echo = TRUE)
```


```{r gt table, echo=FALSE, warning=FALSE}
df <- params$resumen
gt(df) %>% 
          opt_table_lines("all") %>%
          tab_header(
            title = md("**Resumen Servicio**")
          ) %>%
          tab_options(
            column_labels.hidden = TRUE,
            heading.background.color = "#0068C2",
            table.width = pct(100),
            data_row.padding = px(4),
            table.border.right.style = "solid",
            table.border.right.width = px(2),
            table.border.right.color = "gray",
            table.border.left.style = "solid",
            table.border.left.width = px(2),
            table.border.left.color = "gray",
            table.border.top.style = "solid",
            table.border.top.width = px(2),
            table.border.top.color = "gray"
          ) %>% 
          cols_width(
            titulo ~ pct(25),
            valor ~ pct(75)
          ) %>% 
          tab_style(
            style = list(
              cell_fill(color = "gray"),
              cell_text(weight = "bold", size = "x-smaller")
            ),
            locations = cells_body(
              columns = titulo
            )
          ) %>% 
          tab_style(
            style = list(
              cell_text(size = "x-smaller")
            ),
            locations = cells_body(
              columns = valor
            )
          )
```

```{r echo=FALSE, warning=FALSE}
markdown("*****") %>% div(class = "sps-dash")
```

```{r echo=FALSE, warning=FALSE}
df <- params$data_source %>% 
  mutate(
    nombres = str_to_title(nombres),
    apellidos = str_to_title(apellidos)
  ) %>% 
  select(index, rut, nombres, apellidos, cargo, centro_de_costo, fecha_solicitud, fecha_preparacion)
names(df) <- c('n', 'Rut', 'Nombres', 'Apellidos', 'Cargo', 'Contrato', 'Fecha Solicitud', 'Fecha Capacitación')

knitr::kable(df,format = "html", booktabs = T) %>%  
  kableExtra::kable_styling(full_width = F, font_size = 12) %>% 
  column_spec(c(1:ncol(df)), border_right = T) %>% 
  column_spec(2, width = "8em") %>% 
  row_spec(nrow(df), extra_css = "border-bottom: 1px solid;")
# as.data.frame(df)
```
